name: substitute
description: A extended version of indiware.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.8.4+3804

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animations: ^3.0.0
  page_transition: ^2.0.2
  shared_preferences: ^2.2.0
  xml2json: ^6.0.0
  xml: ^7.0.1
  http_auth: ^1.0.0
  flutter_svg: ^2.0.0
  device_info_plus: ^13.2.0
  pretty_qr_code: ^3.6.0
  url_launcher: ^6.1.0

  lottie: ^3.5.1
  fluttertoast: ^10.0.0
  share_plus: ^13.3.0
  introduction_screen: ^4.0.0
  angles: ^2.1.1
  intl: ^0.20.0
  flutter_time_picker_spinner: ^2.0.0
  package_info_plus: ^10.2.1
  http: ^1.0.0
  mobile_scanner: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
      - asset: ./assets/fonts/ProductSans-Light.ttf
  - family: Questrial
    fonts:
      - asset: ./assets/fonts/questrial.ttf
  - family: Crackman
    fonts:
      - asset: ./assets/fonts/crackman.ttf
  assets:
    - assets/img/
    - assets/animations/
    - assets/animations/loading/
